### ISSUE TITLE
Cant download due to virus message

### ISSUE THREAD

**Issue by Evanito** [HoodedDeath/RiskOfDeath-ModManager#1]
Hey, when I hit download on thunderstore, my browser blocks the download because `backblazeb2.com` is a website reported for malware.

Is it possible you could also distribute the executable on the github releases for your project?

Thanks in advance. :)

**Comment by HoodedDeath** [comment]
Seeing as thunderstore storage was recently switching servers, it may have been caused by that. Would you mind testing to see if that issue still happens? And if it turns out to be specific to one mod or a subset of mods, please let me know.

**Comment by Evanito** [comment]
Downloads just fine now :)

Though, can you put a link to https://thunderstore.io/package/HoodedDeath/RiskOfDeathModManager/ at the top of the readme? I had to google it.
